# any environment variables that should not be on Github are sourced from here
if [ -f ~/.local_env ]; then 
  source ~/.local_env
fi

# https://stackoverflow.com/questions/26252591/mac-os-x-and-multiple-java-versions#47699905
if which jenv > /dev/null; then eval "$(jenv init -)"; fi
export PATH="$HOME/.jenv/shims:$PATH"


# https://github.com/bobthecow/git-flow-completion/wiki/Install-Bash-git-completion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# https://github.com/magicmonty/bash-git-prompt
if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR=$(brew --prefix)/opt/bash-git-prompt/share
  #GIT_PROMPT_ONLY_IN_REPO=1
  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
fi
